amqp:
  host: "shrimp.rmq.cloudamqp.com"
  port: "5672"
  virtualHost: "***REMOVED***"
  username: "***REMOVED***"
  password: "***REMOVED***"
  heartbeatTimeout: "60"
  publisher1:
    exchange: eip-guaranteed_delivery
  listener1:
    queue: backend3-person-persisted
    
amq:
  url: "https://mq-us-east-1.anypoint.mulesoft.com/api/v1"
  client_id: "***REMOVED***"
  client_secret: "***REMOVED***"
  publisher1:
    exchange: eip-guaranteeddelivery
  listener1:
    queue: backend3-person-persisted
   
http:
  listener:
    basepath: "/g-delivery"
    port: "8081"
    
api:
  id: "***REMOVED***"